# Generated by Django 2.0.3 on 2018-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180316_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feel',
            field=models.IntegerField(choices=[(1, 'Super!'), (2, 'Nice!'), (3, 'Sad :('), (4, 'Really Bad :<')], default=1),
        ),
    ]
